default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: ravi
      password: ravi
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: ideator_development

test:
  <<: *default
  database: ideator_test

production:
  <<: *default
  database: ideator_production